"""
Django settings for ShortUrl project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8oyq(dqvp=lh71491tj@#mrd^3h7k$3p2b!$iauii=(jm(3#u2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shorturlapp.apps.ShorturlappConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ShortUrl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ShortUrl.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'NAME': 'test',
        'USER': 'root',
        'PASSWORD': 'a1371717153',
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]


# 日志配置

BASE_LOG_DIR = os.path.join(BASE_DIR, 'log')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[asctime][{threadName}:{thread}][task_id:{name}][{filename}:{lineno}]'
                      '[{levelname}][{message}]',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}][{asctime}][{filename}:{lineno}]{message}',
            'style': '{',
        },
        'collect': {
            'format': '{message}',
            'style': '{',
        },
    },
    'filters': {
        # DEBUG为True时的过滤器
      'require_debug_true': {
          '()': 'django.utils.log.RequireDebugTrue',
      }
    },
    'handlers': {
        # 向终端打印的控制器
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        # 默认日志处理器
        'default': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_LOG_DIR, 'short_url_app_info.log'),
            'maxBytes': 1024 * 1024 * 50,  # 日志大小，50M
            'backupCount': 5,  # 日志数量
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        # 记录错误的日志处理器
        'error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_LOG_DIR, 'short_url_app_error.log'),
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        # 默认的logger
        '': {
            'handlers': ['default', 'console', 'error'],
            'level': 'DEBUG',
            'propagate': True
        }
    }
}


# 短链接和长链接的数据库最大长度
LONG_URL_MAX_LENGTH = 200
SHORT_URL_MAX_LENGTH = 50


# 生成的短链接的key的长度

PRODUCE_SHORT_URL_KEY_LENGTH = 6


# 可访问的短链接的key的长度

ACCESSIBLE_SHORT_URL_KEY_LENGTH = {
    'MAX': 50,
    'MIN': 2,
}


# 生成短链接KEY的字符集,和大字符集每次生成的数量

SHORT_URL_KEY_CHAR_SETS = {
    'NUMBERS': True,
    'UPPERCASE_LETTERS': True,
    'LOWWERCASE_LETTERS': True,
    'SPECIAL_SYMBOLS': True,
    'CHINESE': True,
    'EMOJI': True
}
BIG_CHAR_SETS_PRODUCE_NUMBER = {
    'CHINESE': 26,
    'EMOJI': 26,
}


# 生成短链接尝试次数

PRODUCE_SHORT_URL_TRY_TIMES = 2000


# 除了短链接跳转页面以外的路由正则表达式

URLS = {
    'ADMIN': r'^admin/',
    'SHORT_URL': r'^shorturl/',
    'GET_SHORT_URL': r'^setshorturl/',
    'GET_COUNT': r'^getcount/',
    'HOME_PAGE': r'^$'
}

# 状态码
STATUS_CODE = {
    'DEFAULT_ERROR': -1,
    'LONG_URL_FORMAT_ERROR': -2,
    'CHAR_SET_TIME_OUT': -3,
    'SHOURT_URL_EXIST': -4,
    'INPUT_SHORT_URL_ERROR': -5,
    'SHORT_URL_TOO_LONG_ERROR': -6,
    'LONG_URL_TOO_LONG_ERROR': -7,
    'SHOURT_URL_NOT_EXIST': -8,
    'OK': 0,
}
