# Generated by Django 2.1 on 2019-04-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long_url', models.CharField(max_length=50)),
                ('short_url', models.CharField(max_length=50)),
            ],
        ),
    ]
