# Generated by Django 2.1 on 2019-04-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='long_url',
            field=models.CharField(max_length=200),
        ),
    ]
